version: "3"

services:
  api:
    build:
      # Make the project dir the context for the build.
      context: ..
      dockerfile: docker/Dockerfile
    image: pedigree-cats-service
    command:  uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    networks:
      - pedigree-cats-service_network

networks:
  pedigree-cats-service_network:
    driver: bridge